<a href="https://colab.research.google.com/github/meenalsingh5925-creator/Getting-started-with-hugging-face/blob/main/Gettingstartedwithhuggingface(part2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [176]:
!pip install -q "transformers<5.0.0" accelerate datasets evaluate

In [177]:
import transformers, accelerate, datasets, torch, numpy as np

print(transformers.__version__)
print(accelerate.__version__)
print(datasets.__version__)
print(torch.__version__)
print(np.__version__)


4.57.6
1.14.0
4.8.5
2.11.0+cu128
2.1.3


In [178]:
from transformers import AutoModel

In [179]:
model = AutoModel.from_pretrained("bert-base-uncased")

In [180]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [181]:
from transformers import AutoModelForSequenceClassification

In [182]:
model2 = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels = 2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [183]:
model2

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [184]:
model3 = AutoModelForSequenceClassification.from_pretrained("distilbert/distilbert-base-uncased-finetuned-sst-2-english")
model3

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)


# Putting together

In [185]:
from transformers import AutoTokenizer

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

In [186]:
model.config

DistilBertConfig {
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "dtype": "float32",
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.57.6",
  "vocab_size": 30522
}

In [187]:
sent = "I love Hugging face"
inputs = tokenizer(sent, return_tensors = "pt")

In [188]:
inputs

{'input_ids': tensor([[  101,  1045,  2293, 17662,  2227,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}

In [189]:
outputs = model(**inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-4.2173,  4.5582]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [190]:
d = {'a': 10, 'b': 20}

def fun(a, b):
  return a+b

print(fun(d['a'], d['b']))
print(fun(**d))

30
30


In [191]:
outputs.logits[0]

tensor([-4.2173,  4.5582], grad_fn=<SelectBackward0>)

In [192]:
import torch
probs = torch.softmax(outputs.logits, dim = -1) # dim = 1
probs


tensor([[1.5445e-04, 9.9985e-01]], grad_fn=<SoftmaxBackward0>)

In [193]:
predicted_class = torch.argmax(probs, dim = -1)
predicted_class

tensor([1])

In [194]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [195]:
l = [1, 2, 6, 7, 8]
l[-1]

8

# Datasets

In [196]:
from datasets import load_dataset

In [197]:
dataset = load_dataset("imdb")

In [198]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [199]:
dataset["train"][2000]

{'text': 'Darcy and her young daughter Pamela are heading out to the country where her mum\'s boyfriend Peter left his doctor\'s position in the city to become a writer and fix up a bed and breakfast inn. Although this inn has a terrible past and Pamela learns from one the girl\'s who lives in the town that a deformed witch once reside in that house. They called her the \'Tooth Fairy\' as she would kill kids after getting their last baby tooth. This work on the inn, has awoken the \'Tooth Fairy\'. Now she has her sights on Pamela and her last baby tooth, but if any gets in the way they face the same fate that awaits Pamela.<br /><br />This flick\'s old folk myth of the \'Tooth Fairy\' doesn\'t paint her in a very generous way, as you would believe when you were a child. Don\'t they just love turning happy childhood memories into nightmares! Another one which did fall into the same category was "Darkness Falls (2003)". I can\'t compare how similar they are in the premises, because I hav

# map

In [200]:
!pip install datasets

from datasets import load_dataset

fb_data = load_dataset("csv", data_files = "Student_feedback.csv")
fb_data

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['feedback', 'labels'],
        num_rows: 7
    })
})

In [201]:
# @title
import pandas as pd

feedback_data = {
    "feedback": [
        "The course content was very well structured and informative.",
        "The lectures were easy to understand.",
        "I really enjoyed the practical sessions and assignments.",
        "The instructor explained concepts clearly.",
        "The workload was heavy and deadlines were stressful.",
        "The examples used in class made learning easy.",
        "I felt the course could have been more interactive."
    ],
    # ADD THIS: Manual labels (1=positive, 0=negative)
    "labels": [1, 0, 1, 0, 0, 1, 0]
}

df = pd.DataFrame(feedback_data)

df.to_csv("Student_feedback.csv", index=False)


In [202]:
fb_data = fb_data['train'].train_test_split(test_size = 0.25)
fb_data

DatasetDict({
    train: Dataset({
        features: ['feedback', 'labels'],
        num_rows: 5
    })
    test: Dataset({
        features: ['feedback', 'labels'],
        num_rows: 2
    })
})

In [203]:
def tokenize_function(example):
  return tokenizer(
      example['feedback'],
      truncation = True,
      padding = "max_length"
  )
# tokenized_dataset = dataset.map(tokenize_function, batched = False)
fb_tokenized_dataset = fb_data.map(tokenize_function, batched = False)
fb_tokenized_dataset

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['feedback', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 5
    })
    test: Dataset({
        features: ['feedback', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 2
    })
})

# Training/Finetuning

# Gradio

In [204]:
! pip show gradio -q

In [205]:
import gradio as gr

In [206]:
# function
# inputs
# outputs
# interface
# launch

In [207]:
def function(name):
  return f"Hello {name}"

In [208]:
interface = gr.Interface(fn = function, inputs = 'text', outputs = "text")

In [209]:
interface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://d69cc59acd7b1a89d1.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
